const CONFIG={SWIGGY_URL:"",ZOMATO_URL:"",INSTAGRAM_URL:"",CONTACT_URL:""};
const MENU=[{name:"Tamarind Pulihora",category:"rice",description:"Tangy, nutty and comforting.",signature:true},{name:"Lemon Pulihora",category:"rice",description:"Bright, familiar and fresh."},{name:"Zeera Rice",category:"rice",description:"Fragrant cumin-seasoned rice."},{name:"Tomato Rice",category:"rice",description:"Warm, homely tomato rice."},{name:"Kothimeera Rice",category:"rice",description:"Fresh coriander-led comfort."},{name:"Pudina Rice",category:"rice",description:"Aromatic mint rice."},{name:"Pappu Charu Rice",category:"rice",description:"Rice with a comforting Andhra classic."},{name:"Pappu Aavakai Rice",category:"rice",description:"A familiar pairing with character."},{name:"Curd Rice",category:"rice",description:"Cool, simple and comforting."},{name:"Chicken Pulav",category:"chicken",description:"A hearty bowl of fragrant rice and chicken."},{name:"Chicken Fry",category:"chicken",description:"Crisp, spiced chicken."},{name:"Chicken Fry Piece Biriyani",category:"chicken",description:"A generous biriyani bowl."},{name:"Bagara Rice + Veg Curry",category:"chicken",description:"Fragrant rice with a vegetable curry."},{name:"Omelette Variants",category:"egg",description:"Simple egg favourites, made to order."}];
const INGREDIENTS=[{name:"RICE",copy:"Soft enough to carry all the good stuff."},{name:"TAMARIND",copy:"Tangy enough to wake up the whole bowl."},{name:"CORIANDER",copy:"Freshness that cuts through every bite."},{name:"LEMON",copy:"Bright, clean and unmistakably familiar."},{name:"CHILLI",copy:"A little kick. Nothing that needs showing off."},{name:"PEANUTS",copy:"Crunch matters. Especially in a good pulihora."},{name:"SPICES",copy:"Warm, layered flavour in the background."},{name:"CURRY LEAVES",copy:"That unmistakable tempering finish."}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function renderMenu(filter="all"){const root=$("#menuList"),items=filter==="all"?MENU:MENU.filter(x=>x.category===filter);root.innerHTML=items.length?items.map((x,i)=>`<article class="menu-item"><span class="menu-index">${String(i+1).padStart(2,"0")}</span><div><div class="menu-name">${x.name}${x.signature?'<small class="signature-label">OUR SIGNATURE</small>':''}</div><div class="menu-desc">${x.description}</div></div><span class="menu-price">₹XX</span></article>`).join(""):`<div class="menu-item"><span></span><div><div class="menu-name">Coming soon</div><div class="menu-desc">This category has no menu items yet.</div></div><span>—</span></div>`;$$('#menuList .menu-item').forEach((el,i)=>{el.classList.add('reveal');requestAnimationFrame(()=>setTimeout(()=>el.classList.add('in'),i*35))})}
renderMenu();
$$('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{$$('.tabs button').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-selected','false')});btn.classList.add('active');btn.setAttribute('aria-selected','true');renderMenu(btn.dataset.filter)}));
$$('[data-config]').forEach(a=>{const val=CONFIG[a.dataset.config];if(val){a.href=val;a.target='_blank';a.rel='noopener noreferrer'}else{a.title=`${a.dataset.config} is not configured yet`;a.addEventListener('click',e=>e.preventDefault())}});
const header=$("#header");window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>30),{passive:true});
const menuButton=$("#menuButton"),mobileNav=$("#mobileNav");menuButton.addEventListener('click',()=>{const open=mobileNav.hasAttribute('hidden');open?mobileNav.removeAttribute('hidden'):mobileNav.setAttribute('hidden','');menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close menu':'Open menu')});$$('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>{mobileNav.setAttribute('hidden','');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Open menu')}));
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(!id||id==='#'||a.dataset.config)return;const el=$(id);if(!el)return;e.preventDefault();el.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});history.replaceState(null,'',id)}));
const revealIO=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');revealIO.unobserve(e.target)}}),{threshold:.12});$$('section:not(.hero)').forEach(sec=>sec.querySelectorAll('h2,p,.section-label,.menu-head,.kitchen li,.wall article,.social-card').forEach(el=>{el.classList.add('reveal');revealIO.observe(el)}));
function setIngredient(name){const item=INGREDIENTS.find(x=>x.name===name)||INGREDIENTS[1];$$('.ingredient-chip-large').forEach(x=>x.classList.toggle('active',x.textContent===item.name));$("#ingredientNote").innerHTML=`${item.name}<br><span>${item.copy}</span>`}
INGREDIENTS.forEach((item,i)=>{const b=document.createElement('button');b.className='ingredient-chip-large';b.type='button';b.textContent=item.name;b.addEventListener('click',()=>setIngredient(item.name));(i<4?$('#ingredientLeft'):$('#ingredientRight')).appendChild(b)});setIngredient('TAMARIND');
const motionOK=!matchMedia('(prefers-reduced-motion: reduce)').matches,assembly=$('#assembly'),chips=$$('.ingredient-chip'),layers=$$('.food-layer'),steams=$$('.steam');function updateAssembly(){if(!motionOK){layers.forEach(x=>{x.style.opacity='1';x.style.transform='none'});steams.forEach(x=>x.style.opacity='.45');return}const r=assembly.getBoundingClientRect(),vh=innerHeight,progress=Math.max(0,Math.min(1,(vh*.88-r.top)/(vh*1.25)));chips.forEach((c,i)=>{const p=Math.max(0,Math.min(1,(progress-.08-i*.07)/.45)),a=i*.72;c.style.transform=`translate(${Math.cos(a)*150*(1-p)}px,${Math.sin(a)*120*(1-p)}px) scale(${.9+.1*p})`;c.style.opacity=String(.18+.82*p)});layers.forEach((x,i)=>{const p=Math.max(0,Math.min(1,(progress-(.18+i*.17))/.35));x.style.opacity=String(p);x.style.transform=`translateY(${35*(1-p)}px) scale(${.78+.22*p})`});const sp=Math.max(0,Math.min(1,(progress-.78)/.22));steams.forEach(x=>x.style.opacity=String(.45*sp))}updateAssembly();if(motionOK){window.addEventListener('scroll',updateAssembly,{passive:true});window.addEventListener('resize',updateAssembly)}
