const CONFIG = { SWIGGY_URL: "", ZOMATO_URL: "", INSTAGRAM_URL: "", CONTACT_URL: "" };
const MENU = [
["Tamarind Pulihora","rice","Tangy, nutty and comforting.",true],["Lemon Pulihora","rice","Bright, familiar and fresh."],["Zeera Rice","rice","Fragrant cumin-seasoned rice."],["Tomato Rice","rice","Warm, homely tomato rice."],["Kothimeera Rice","rice","Fresh coriander-led comfort."],["Pudina Rice","rice","Aromatic mint rice."],["Pappu Charu Rice","rice","Rice with a comforting Andhra classic."],["Pappu Aavakai Rice","rice","A familiar pairing with character."],["Curd Rice","rice","Cool, simple and comforting."],["Chicken Pulav","chicken","A hearty bowl of fragrant rice and chicken."],["Chicken Fry","chicken","Crisp, spiced chicken."],["Chicken Fry Piece Biriyani","chicken","A generous biriyani bowl."],["Bagara Rice + Veg Curry","chicken","Fragrant rice with a vegetable curry."],["Omelette Variants","egg","Simple egg favourites, made to order."]
];
const grid=document.getElementById("menuGrid");
function renderMenu(filter="all"){if(!grid)return;const items=filter==="all"?MENU:MENU.filter(x=>x[1]===filter);grid.innerHTML=items.map((x,i)=>`<article class="menu-item"><span class="menu-index">${String(i+1).padStart(2,"0")}</span><div><div class="menu-name">${x[0]}${x[3]?'<small class="signature-label">OUR SIGNATURE</small>':''}</div><div class="menu-desc">${x[2]}</div></div><span class="menu-price">₹XX</span></article>`).join("");}
renderMenu();
document.querySelectorAll(".tabs button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderMenu(b.dataset.filter||"all");}));
document.querySelectorAll("[data-config]").forEach(a=>{const v=CONFIG[a.dataset.config];if(v){a.href=v;a.target="_blank";a.rel="noopener noreferrer";}else a.addEventListener("click",e=>e.preventDefault());});
const button=document.getElementById("menuButton"),nav=document.getElementById("mobileNav");
if(button&&nav){button.addEventListener("click",()=>{const open=nav.classList.toggle("open");button.setAttribute("aria-expanded",open);nav.setAttribute("aria-hidden",!open);});nav.querySelectorAll("a[href^='#']").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");button.setAttribute("aria-expanded","false");nav.setAttribute("aria-hidden","true");}));}
/* Section navigation: explicit smooth scrolling, with no scroll-jacking. */
document.querySelectorAll("a[href^='#']").forEach(a=>{if(a.dataset.config||a.closest(".tabs"))return;a.addEventListener("click",e=>{const id=a.getAttribute("href");if(!id||id==="#")return;const target=document.querySelector(id);if(!target)return;e.preventDefault();const y=target.getBoundingClientRect().top+window.scrollY-80;window.scrollTo({top:y,behavior:"smooth"});});});
const note=document.getElementById("ingredientNote");document.querySelectorAll(".cloud-tag").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".cloud-tag").forEach(x=>x.classList.remove("active"));t.classList.add("active");if(note)note.textContent=t.dataset.copy||"";}));
